name: daily_report_workflow

on:
  schedule:
    - cron: '00 9 * * *'
  workflow_dispatch:

jobs:
  api-test:
    runs-on: ubuntu-latest
    steps:
      - name: api-tests
        run: echo "api test"