name: api_test_every_midnight

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  api-test:
    runs-on: ubuntu-latest
    steps:
      - name: api-tests
        run: echo "api test"
