name: api_test_daily_workflow

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  api-test:
    runs-on: ubuntu-latest
    steps:
      - name: api-tests
        run: echo "api test"