name: daily_report_workflow

on:
  schedule:
    - cron: '50 7 * * *'
  workflow_dispatch:

jobs:
  api-test:
    suns-on: ubuntu-latest
    steps:
      - name: api-tests
        run: echo "api test"