name: api-test
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    name: javaApiTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-dept: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v1

      -  name: Run unit test
      - run: mvn clean test -Punit-test

