name: api-test
on:
  push:
    branches:
      - master
  workflow_dispatch: null
jobs:
  build:
    name: javaApiTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-dept: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run api tests
        run: mvn clean test



